Check the required tools at the beginning of running chameleon daemon
Chameleon daemon needs some required tools, e.g. i2cget, i2cset, i2cdump,
memtool, memdump2file, etc. It causes a problem if missing one of these tools.
Check the required tools at the beginning to prevent this problem.

BUG=chromium:345541
TEST=manual
Inside Chameleon system:
$ mv /usr/bin/memtool /usr/bin/memtool.backup
Run chameleond:
$ run_chameleond --log -
2014-02-17 02:00:43,134 INFO Load module fpga_driver...
2014-02-17 02:00:43,172 ERROR Failed to start Chameleon server.
Traceback (most recent call last):
  File "/usr/bin/run_chameleond", line 52, in main
    ChameleonServer(options.driver, *args, **kwargs).RunServer(
  File "/usr/lib/python2.7/site-packages/chameleond/chameleon_server.py", line 2
0, in __init__
    self._driver = self._LoadDriver(driver)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/chameleond/drivers/fpga_driver.py", lin
e 68, in __init__
    self._CheckRequiredTools()
  File "/usr/lib/python2.7/site-packages/chameleond/drivers/fpga_driver.py", lin
e 81, in _CheckRequiredTools
    raise FpgaDriverError('Required tool %s not existed' % path)
FpgaDriverError: Required tool /usr/bin/memtool not existed

Change-Id: Ic083ac9ad5bde4534089d03faaaf6ab652de3d70
Reviewed-on: https://chromium-review.googlesource.com/188162
Reviewed-by: Wai-Hong Tam <waihong@chromium.org>
Commit-Queue: Wai-Hong Tam <waihong@chromium.org>
Tested-by: Wai-Hong Tam <waihong@chromium.org>